jobs:
  promote:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install pandas
        run: |
          python -m pip install --upgrade pip
          pip install pandas

      - name: Promote staged → splits.csv
        run: |
          python - <<'PY'
          import pandas as pd, os, sys
          STAGED = "audit_out/splits_staged.csv"
          if not os.path.exists(STAGED) or os.path.getsize(STAGED) == 0:
              print("no staged file; bail"); sys.exit(0)
          df = pd.read_csv(STAGED, dtype=str).fillna("")
          if len(df) == 0:
              print("staged empty; bail"); sys.exit(0)
          req = {"league", "home_team", "away_team"}
          if not req.issubset(df.columns):
              print("missing required cols; bail"); sys.exit(0)
          if "league" in df.columns:
              df = df[df["league"].astype(str) != "MIXED"]
          if len(df) == 0:
              print("only MIXED rows; bail"); sys.exit(0)
          df.to_csv("splits.csv", index=False)
          print("PROMOTE_OK rows:", len(df))
          PY

      - name: Commit promoted splits.csv
        run: |
          git config user.name "splits-bot"
          git config user.email "splits-bot@example.com"
          git add splits.csv
          git commit -m "promote: staged → splits.csv [skip ci]" || echo "no changes"
          git push
