- name: Commit clean splits with rebase & retry
  run: |
    set -euo pipefail
    git config user.name  "splits-bot"
    git config user.email "bot@users.noreply.github.com"

    BRANCH="${GITHUB_REF_NAME:-main}"

    # Stage & commit if there are changes
    git add splits.csv splits_clean.csv || true
    if git diff --cached --quiet; then
      echo "No changes to commit."
      exit 0
    fi
    git commit -m "splits-guard: promote clean → splits.csv (no dictionary)" || true

    # Rebase + retry push (prefer ours for generated files)
    for attempt in 1 2 3 4 5; do
      if git push origin "HEAD:${BRANCH}"; then
        echo "Pushed on attempt $attempt"
        exit 0
      fi
      echo "Push failed (attempt $attempt). Rebasing onto origin/${BRANCH}…"
      git fetch origin "${BRANCH}"
      if ! git pull --rebase origin "${BRANCH}"; then
        echo "Rebase conflict; preferring ours for generated artifacts."
        git checkout --ours -- splits.csv splits_clean.csv || true
        git add splits.csv splits_clean.csv || true
        git rebase --continue || true
      fi
      sleep $((RANDOM%5+2))
    done
    echo "Failed to push after retries." >&2
    exit 1
