name: Splits Guard/Normalizer
on:
  schedule: [{ cron: "*/15 * * * *" }]
  workflow_dispatch:
permissions:
  contents: write
jobs:
  guard:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }
      - name: Deps
        run: |
          python -m pip install --upgrade pip
          pip install pandas
      - name: Run guard
        run: |
          mkdir -p audit_out
          test -f splits.csv || printf "timestamp,away_team,home_team,market,tickets_pct,handle_pct,line,source\n" > splits.csv
          python scripts/splits_guard_clean.py --in splits.csv --out splits_clean.csv --teams scripts/team_dictionary.json --promote
      - name: Commit cleaned splits
        run: |
          set -e
          git config user.name  "splits-bot"
          git config user.email "bot@users.noreply.github.com"
          git add splits.csv splits_clean.csv || true
          git diff --cached --quiet || git commit -m "splits-guard: promote clean → splits.csv"
          git push
