name: Splits Guard/Normalizer
on:
  schedule: [{ cron: "*/15 * * * *" }]
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - "scripts/splits_guard_clean.py"
      - "splits.csv"
      - "audit_out/splits_staged.csv"
concurrency: { group: splits-guard, cancel-in-progress: true }

jobs:
  run:
    runs-on: ubuntu-latest
    permissions: { contents: write }
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }
      - name: Deps
        run: |
          python -m pip install --upgrade pip
          pip install pandas
      - name: Clean & promote splits
        run: python scripts/splits_guard_clean.py
      - name: Commit if changed
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add splits.csv splits_clean.csv splits_flagged.csv || true
          if git diff --staged --quiet; then
            echo "No changes."
          else
            git commit -m "CI(splits-guard): clean & promote splits" && git push
          fi
