name: Sheets → Twitter ingest
on:
  workflow_dispatch:
  schedule:
    - cron: "*/15 * * * *"

jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with: { fetch-depth: 0 }
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }
      - name: Ingest tweets CSV (secret or fallback)
        run: |
          set -e
          mkdir -p sources/sheets/twitter
          if [ -n "${SHEETS_CSV_URL:-}" ]; then
            curl -fsSL "${SHEETS_CSV_URL}&nocache=$(date +%s)" -o sources/sheets/twitter/tweets.csv || true
          fi
          if [ ! -s sources/sheets/twitter/tweets.csv ]; then
            printf "timestamp,handle,text,url\n" > sources/sheets/twitter/tweets.csv
          fi
      - name: Commit tweets.csv if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add sources/sheets/twitter/tweets.csv
          if git diff --staged --quiet; then echo "No tweet updates."; else git commit -m "CI(Twitter ingest): refresh tweets.csv [skip ci]"; git push; fi
