name: twitter-text

on:
  schedule:
    - cron: "*/15 * * * *"   # every 15 minutes
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  analyze-twitter-text:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install pandas

      - name: Ensure dirs
        run: |
          mkdir -p ./sources/sheets/twitter
          mkdir -p ./audit_out

      - name: Fetch Google Sheet (tweets.csv)
        env:
          SHEETS_CSV_URL: ${{ secrets.SHEETS_CSV_URL }}
        run: |
          if [ -z "$SHEETS_CSV_URL" ]; then
            echo "SHEETS_CSV_URL secret is missing"; exit 1
          fi
          curl -fsSL "$SHEETS_CSV_URL" -o ./sources/sheets/twitter/tweets.csv
          wc -l ./sources/sheets/twitter/tweets.csv || true
          head -5 ./sources/sheets/twitter/tweets.csv || true

      - name: Analyze Twitter text (graded)
        run: |
          python scripts/analyze_twitter_text.py \
            --csv  ./sources/sheets/twitter/tweets.csv \
            --dict ./dictionaries \
            --out  ./audit_out/twitter_text_signals.csv

      - name: Commit outputs
        run: |
          git config user.name "github-actions"
          git config user.email "actions@users.noreply.github.com"
          git add ./sources/sheets/twitter/tweets.csv ./audit_out/twitter_text_signals.csv
          git commit -m "ci: update twitter_text_signals (auto)" || echo "No changes to commit"
          git push
